trainer:
    callbacks:
    #   - class_path: callbacks.LogTestCallback
    #   - class_path: callbacks.LogTrainBinaryExtCallback
      - class_path: callbacks.SaveEmbedCallback
    precision: 32-true
    devices: 1
# ckpt_path: null
# ckpt_path: /ceoas/emapr/sundial/checkpoints/all224_glkn/epoch=0124_val_loss=0.354_fcn_dice_frozen.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/all224_glkn/epoch=0123_val_loss=0.362_fcn_dice_unfrozen.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/all224_glkn/epoch=0127_val_loss=0.414_fcn_dice_nockpt.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/all224_glkn/epoch=0113_val_loss=0.334_unet3d_dice.ckpt
ckpt_path: /home/ceoas/truongmy/emapr/sundial/checkpoints/all224_glkn/epoch=0026_val_loss=0.684_unet3dmid_dice.ckpt
# criterion:
#     class_path: DiceLoss
# activation:
#     class_path: Sigmoid