trainer:
    callbacks:
      - class_path: callbacks.LogTrainCallback
      - class_path: StochasticWeightAveraging
        init_args:
            swa_lrs: 0.0001
            device: null
    max_epochs: 1024
    enable_progress_bar: true
    strategy: auto
    devices: 1
    num_nodes: 1
    accumulate_grad_batches: 4
    log_every_n_steps: 8
    precision: bf16-mixed
model_checkpoint:
    monitor: val_loss
    mode: min
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0001
lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
        T_max : 128
criterion:
    class_path: RMSELoss
