.ONE_SHELL:
SHELL := /bin/bash

.EXPORT_ALL_VARIABLES:
.SILENT:
.PHONY:

ifndef SUNDIAL_BASE_PATH
SUNDIAL_BASE_PATH := $(shell pwd -P)
endif

ifndef SUNDIAL_ENV_NAME 
SUNDIAL_ENV_NAME := sundial
endif

ifndef SUNDIAL_PROCESSING
SUNDIAL_PROCESSING := hpc
endif

ifndef SUNDIAL_NODELIST
SUNDIAL_NODELIST :=
endif

ifndef SUNDIAL_PACKAGE_FORMAT
SUNDIAL_PACKAGE_FORMAT := tar
endif

ifndef SUNDIAL_BASE_PATH
SUNDIAL_BASE_PATH := $(shell pwd)
endif

SUNDIAL_EXPERIMENT_BASE_NAME := $(SUNDIAL_EXPERIMENT_PREFIX)_$(SUNDIAL_SHAPE_NAME)
ifndef SUNDIAL_EXPERIMENT_SUFFIX
SUNDIAL_EXPERIMENT_FULL_NAME := $(SUNDIAL_EXPERIMENT_BASE_NAME)
else
SUNDIAL_EXPERIMENT_FULL_NAME := $(SUNDIAL_EXPERIMENT_BASE_NAME)_$(SUNDIAL_EXPERIMENT_SUFFIX)
endif

default:
	echo "Welcome to Sundial!"
	echo
	echo "	  Current config directory: configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)"
	echo
	echo "    Methods:"
	echo
	echo		Setup methods for starting experiment.
	echo
	echo "        setup_env:      Sets up Sundial directories and environment. The existing environment will be overwritten."
	echo "        setup:          Sets up Sundial experiment directories and config files using defaults found in **src/settings.py.**"
	echo
	echo		Sampling methods for generating image chips and indexing them.
	echo
	echo "        download:       Downloads image chips for experiment using sample polygons generated by sample method."
	echo "        annotate:       Collects image annotations for experiment using sample polygons generated by sample method."
	echo "        stats:           Creates indicies for training from chip and anno data using indexer in configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)/pipeline.yaml."
	echo
	echo		Training methods. There should be base yaml with model information at configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)/base.yaml 
	echo
	echo "        fit:            Train model using configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)/fit.yaml. This will run a full optimization routine."
	echo "        validate:       Validate model using configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)/validate.yaml. This will run a single epoch."
	echo "        test:           Test model using configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)/test.yaml. This will run a single epoch."
	echo "        predict:        Predict an image using configs/$(SUNDIAL_EXPERIMENT_BASE_NAME)/predict.yaml. This will run a single epoch."
	echo "        package:        Convert predictions in predictions/$(SUNDIAL_EXPERIMENT_BASE_NAME) to GeoTIFF and compress for download."
	echo
	echo		Debug / help methods
	echo
	echo "        status:         Check status of all jobs for user."
	echo "        vars:           Print all Sundial variables."
	echo "        (method)_err:   Print ERRORs and CRITICALs in log file and print stderr from file on HPC."
	echo
	echo		Cleaning methods
	echo
	echo "        clean_expt:     Removes all logs, checkpoints, and predictions for experiment."
	echo "        clean_logs:     Removes all logs for experiment."
	echo "        clean_dnld:     Removes all imagery data for experiment."
	echo "        clean_anno:     Removes all annotation data for experiment."
	echo "        clean_nuke:     Removes all data for experiment including configs."
	echo
	echo "    Variables:"
	echo "    These may be set as submake flags or as environment variables."
	echo
	echo "        SUNDIAL_BASE_PATH:           Base path for Sundial scripts. Default: 'shell pwd' of makefile"
	echo "        SUNDIAL_SHAPE_NAME:          Shapefile name. REQUIRED"
	echo "        SUNDIAL_EXPERIMENT_PREFIX:   Sundial experiment name prefix used for experiment naming. REQUIRED"
	echo "        SUNDIAL_EXPERIMENT_SUFFIX:   Experiment suffix used only for logging."
	echo "        SUNDIAL_ENV_NAME:            Sundial environment name. Default: 'sundial'"
	echo "        SUNDIAL_PROCESSING:          Sundial processing method. Default: 'hpc'"
	echo "        SUNDIAL_NODELIST:            Node within hpc to run job. Default: any node"
	echo "        SUNDIAL_GPU_PARTITION:       Partition within hpc to run gpu based jobs."
	echo "        SUNDIAL_CPU_PARTITION:       Partition within hpc to run cpu based jobs."
	echo "        SUNDIAL_PACKAGE_FORMAT:      Format to package predictions. Default: 'tar'"
	echo

setup_env:
	echo "Setting up directories for $(SUNDIAL_BASE_PATH) and conda environment "$(SUNDIAL_ENV_NAME)".";
	mkdir -p $(SUNDIAL_BASE_PATH)/experiments
	if [[ "$(ARCH)" == aarch64 ]]; then \
		conda env create -f $(SUNDIAL_BASE_PATH)/environment_a64.yaml -n $(SUNDIAL_ENV_NAME) -y; \
	else \
		conda env create -f $(SUNDIAL_BASE_PATH)/environment_x86.yaml -n $(SUNDIAL_ENV_NAME) -y; \
	fi; \
	echo "Sundial setup complete!";

setup: _experiment_name_check
	echo "Setting up Sundial experiment for $(SUNDIAL_EXPERIMENT_BASE_NAME)...";
	$(eval export SUNDIAL_METHOD=base) 
	mkdir -p $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME);
	if [[ -d $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/configs ]]; then \
		echo "WARNING: Configs directory found. To restart experiment from scratch, use 'make clean_nuke' then 'make setup'..."; \
	else \
		echo "Generating Sundial config files for experiment with values from settings.py..."; \
		python $(SUNDIAL_BASE_PATH)/src/config_utils.py; \
	fi;

clink: _experiment_name_check
	if [[ -z "$(SSOURCE)" ]]; then \
		echo "Please provide a source experiment to copy from in variable "SSOURCE" (eg 'make clink SSOURCE=14k')..."; \
		exit 1; \
	fi; \
	source_exp=$(SSOURCE)_$(SUNDIAL_SHAPE_NAME); \
	echo "Copying Sundial experiment $$source_exp configs to $(SUNDIAL_EXPERIMENT_BASE_NAME)..."; \
	cp -r $(SUNDIAL_BASE_PATH)/configs/$$source_exp $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/configs; \
	rm -rvf $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/configs/pipeline.yaml; \
	echo "WARNING: This will create soft links to the source sammple data and sample config file."; \
	ln -s $(SUNDIAL_BASE_PATH)/experiments/$$source_exp/imagery $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/imagery; \
		ln -s $(SUNDIAL_BASE_PATH)/experiments/$$source_exp/annotations $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/annotations; \
	ln -s $(SUNDIAL_BASE_PATH)/experiments/$$source_exp/configs/pipeline.yaml $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/configs/pipeline.yaml;

vars: _experiment_name_check
	echo "SUNDIAL_BASE_PATH: $(SUNDIAL_BASE_PATH)";
	echo "SUNDIAL_SHAPE_NAME: $(SUNDIAL_SHAPE_NAME)";
	echo "SUNDIAL_EXPERIMENT_PREFIX: $(SUNDIAL_EXPERIMENT_PREFIX)";
	echo "SUNDIAL_EXPERIMENT_SUFFIX: $(SUNDIAL_EXPERIMENT_SUFFIX)";
	echo "SUNDIAL_EXPERIMENT_BASE_NAME: $(SUNDIAL_EXPERIMENT_BASE_NAME)";
	echo "SUNDIAL_EXPERIMENT_FULL_NAME: $(SUNDIAL_EXPERIMENT_FULL_NAME)";
	echo "SUNDIAL_ENV_NAME: $(SUNDIAL_ENV_NAME)";
	echo "SUNDIAL_PROCESSING: $(SUNDIAL_PROCESSING)";
	echo "SUNDIAL_NODELIST: $(SUNDIAL_NODELIST)";
	echo "SUNDIAL_NUM_NODES: $(SUNDIAL_NUM_NODES)";
	echo "SUNDIAL_MEM: $(SUNDIAL_MEM)";
	echo "SUNDIAL_GPU_PARTITION: $(SUNDIAL_GPU_PARTITION)";
	echo "SUNDIAL_CPU_PARTITION: $(SUNDIAL_CPU_PARTITION)";
	echo "SUNDIAL_PACKAGE_FORMAT: $(SUNDIAL_PACKAGE_FORMAT)";


download: _download
	echo "Downloading image chips for $(SUNDIAL_EXPERIMENT_FULL_NAME). Sit tight...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_CPU_PARTITION))
	$(MAKE) -s _run

annotate: _annotate
	echo "Collecting image annotations for $(SUNDIAL_EXPERIMENT_FULL_NAME). This might take a sec...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_CPU_PARTITION))
	$(MAKE) -s _run

stats: _stats
	echo "Creating indicies for $(SUNDIAL_EXPERIMENT_FULL_NAME)...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_CPU_PARTITION))
	$(MAKE) -s _run

fit: _fit
	echo "Training model for $(SUNDIAL_EXPERIMENT_FULL_NAME)... This may take a while...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_GPU_PARTITION))
	$(MAKE) -s _run

validate: _validate
	echo "Validating model for $(SUNDIAL_EXPERIMENT_FULL_NAME)... Go ahead and hold your breath...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_GPU_PARTITION))
	$(MAKE) -s _run

test: _test
	echo "Testing model for $(SUNDIAL_EXPERIMENT_FULL_NAME)... Use 'make test_err' to check for critical errors...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_GPU_PARTITION))
	$(MAKE) -s _run

predict: _predict
	echo "Making predictions for $(SUNDIAL_EXPERIMENT_FULL_NAME)... Lets see if this works!";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_GPU_PARTITION))
	$(MAKE) -s _run

package: _package
	echo "Packaging predictions for $(SUNDIAL_EXPERIMENT_FULL_NAME)...";
	$(eval export SUNDIAL_PARTITION=$(SUNDIAL_CPU_PARTITION))
	$(MAKE) -s _run

status: _hpc_check
	squeue -u $(USER) --format="%.18i %.9P %.40j %.8u %.8T %.10M %.9l %.6D %R";

sample_err: _sample
	$(MAKE) -s _read_err;

annotate_err: _annotate
	$(MAKE) -s _read_err;

download_err: _download
	$(MAKE) -s _read_err;

stats_err: _stats
	$(MAKE) -s _read_err;

fit_err: _fit
	$(MAKE) -s _read_err;

validate_err: _validate
	$(MAKE) -s _read_err;

test_err: _test
	$(MAKE) -s _read_err;

predict_err: _predict
	$(MAKE) -s _read_err;

package_err: _package
	$(MAKE) -s _read_err;

clean_expt: _experiment_name_check
	echo "Cleaning up logs, checkpoints, and predictions for $(SUNDIAL_EXPERIMENT_BASE_NAME).";
	rm -rvf $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_EXPERIMENT_SUFFIX);

clean_logs: _experiment_name_check
	echo "Cleaning up logs for $(SUNDIAL_EXPERIMENT_BASE_NAME).";
	rm -rvf $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/*.log;

clean_dnld: _experiment_name_check
	echo "Cleaning up imagery data for $(SUNDIAL_EXPERIMENT_BASE_NAME).";
	rm -rvf $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/imagery;
	mkdir $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/imagery

clean_anno: _experiment_name_check
	echo "Cleaning up annotation data for $(SUNDIAL_EXPERIMENT_BASE_NAME).";
	rm -rvf $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/annotations/;
	mkdir $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/annotations/;

clean_nuke: _experiment_name_check
	echo "Cleaning up all data for $(SUNDIAL_EXPERIMENT_BASE_NAME).";
	rm -rvf $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME);

_config_dir_check:
	if [[ ! -d $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/configs ]]; then \
		echo "No configs found. Please run make setup first..."; \
		exit 1; \
	fi;

_experiment_name_check:
	if [[ -z "$(SUNDIAL_SHAPE_NAME)" ]]; then \
		echo "Please provide sample name. (eg 'make setup SUNDIAL_SHAPE_NAME=shapefile_name') "; \
		exit 1; \
	fi; \
	if [[ -z "$(SUNDIAL_EXPERIMENT_PREFIX)" ]]; then \
		echo "Please provide a Sundial experiment prefix. (eg 'make setup SUNDIAL_EXPERIMENT_PREFIX=14k')..."; \
		exit 1; \
	fi;


_hpc_check:
	if [[ "$(SUNDIAL_PROCESSING)" != hpc ]]; then \
		echo "This method is only available on an HPC with slurm..."; \
		exit 1; \
	fi;

_sample:
	$(eval export SUNDIAL_METHOD=sample)

_annotate:
	$(eval export SUNDIAL_METHOD=annotate)

_download:
	$(eval export SUNDIAL_METHOD=download)

_stats:
	$(eval export SUNDIAL_METHOD=stats)

_fit:
	$(eval export SUNDIAL_METHOD=fit)

_validate:
	$(eval export SUNDIAL_METHOD=validate)

_test:
	$(eval export SUNDIAL_METHOD=test)

_predict:
	$(eval export SUNDIAL_METHOD=predict)

_package:
	$(eval export SUNDIAL_METHOD=package)

_run: _experiment_name_check
	if [[ "$(SUNDIAL_PROCESSING)" == hpc ]]; then \
		job_name=$(SUNDIAL_METHOD)_$(SUNDIAL_EXPERIMENT_FULL_NAME); \
		if [[ -z "$(SUNDIAL_NODELIST)" ]]; then \
			nodelist=$(shell sinfo -h -p $(SUNDIAL_PARTITION) -o "%N"); \
		else \
			nodelist=$(SUNDIAL_NODELIST); \
		fi; \
		if [[ -z "$(SUNDIAL_NUM_NODES)" ]]; then \
			num_nodes=1; \
		else \
			num_nodes=$(SUNDIAL_NUM_NODES); \
		fi; \
		if [[ "$(SUNDIAL_NUM_NODES)" > 1 ]]; then \
			NCCL_P2P_DISABLE=1; \
			NCCL_DEBUG=INFO; \
		fi; \
		if [[ -z "$(SUNDIAL_MEM)" ]]; then \
			mem=128G; \
		else \
			mem=$(SUNDIAL_MEM); \
		fi; \
		if [[ "$(SUNDIAL_METHOD)" == download || "$(SUNDIAL_METHOD)" == annotate ]]; then \
			cpus=42; \
    else \
			cpus=4; \
		fi; \
		echo "Running on HPC..."; \
		sbatch \
			--job-name=$$job_name \
			--output=$(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).o \
			--error=$(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).e \
			--chdir=$(SUNDIAL_BASE_PATH) \
			--partition=$(SUNDIAL_PARTITION) \
			--nodelist=$$nodelist \
			--nodes=$$num_nodes \
			--mem=$$mem \
			--cpus-per-task=$$cpus \
			--export=ALL \
			$(SUNDIAL_BASE_PATH)/sundial.slurm; \
	else \
		echo "Running on local machine..."; \
		python $(SUNDIAL_BASE_PATH)/src/runner.py; \
	fi;

_read_err: _experiment_name_check
	if [[ -f $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).e ]]; then \
		cat $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).e; \
	fi; \
	if [[ -f $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).log ]]; then \
		cat $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).log | grep ERROR; \
		cat $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).log | grep CRITICAL; \
		tail $(SUNDIAL_BASE_PATH)/experiments/$(SUNDIAL_EXPERIMENT_BASE_NAME)/logs/$(SUNDIAL_METHOD).log; \
	fi;
