model:
    class_path: Prithvi
    init_args:
        prithvi_params:
            model_args:
                decoder_depth: 8
                decoder_embed_dim: 512
                decoder_num_heads: 16
                depth: 12
                embed_dim: 768
                img_size: 256
                in_chans: 6
                num_frames: 3
                num_heads: 12
                patch_size: 16
                tubelet_size: 1
            train_params:
                mask_ratio: 0.75
data:
    class_path: ChipsDataModule
    init_args:
        batch_size: 256
        num_workers: 16
        chip_size: 256
        anno_data_path: null
trainer:
    callbacks:
      - class_path: PrithviCallbacks
    max_epochs: 1024
    strategy: ddp
    devices: 1
    num_nodes: 2
    accumulate_grad_batches: 4
    precision: 16-true
    gradient_clip_val: 0.2
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0001
lr_scheduler:
    class_path: torch.optim.lr_scheduler.StepLR
    init_args:
        step_size: 64
        gamma: 0.7

