trainer:
    callbacks:
      - class_path: callbacks.LogTrainCallback
      - class_path: callbacks.LogTrainMulticlassExtCallback
      - class_path: StochasticWeightAveraging
        init_args:
            swa_lrs: 0.0001
            device: null
    max_epochs: 1024
    strategy: ddp_find_unused_parameters_true
    devices: 2
    num_nodes: 1
    accumulate_grad_batches: 8
    precision: bf16-mixed
    gradient_clip_val: 5
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0001
lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
        T_max : 128
criterion:
    class_path: SSIMLoss
activation:
    class_path: Sigmoid
