datetime_column: "yod"
file_type: ZARR
gee_workers: 42
gee_stratafied_config: null
groupby_columns: ["yod"]
io_limit: 32
look_range: 5
method: centroid_shift
num_points: 4096
num_workers: 64
overwrite: false
pixel_edge_size: 256
postprocess_actions: []
predict_ratio: 0.0
preprocess_actions:
    - column: predicted
      action: "!="
      targets: ['%_Stable', '%_UknAbruptDisturbance']
projection: EPSG:5070
generate_time_combinations: false
scale: 30
strata_columns: ["predicted"]
test_ratio: 0.04
validate_ratio: 0.2
