file_type: ZARR
gee_workers: 42
gee_stratafied_config: null
groupby_columns: ["year"]
io_limit: 32
look_range: 6
method: centroid_shift
num_points: 1024
num_workers: 64
overwrite: false
pixel_edge_size: 256
postprocess_actions:
    - data: anno
      action: sum
      operator: ">="
      targets: 8192
predict_ratio: 0.0
preprocess_actions:
    - column: dca_cat
      action: "!="
      targets: ['multi-agent "complexes"', "cankers", "rusts", "wild animals", "unknown"]
    - column: dca_cat
      action: replace
      targets: [["defoliators", "foliage and shoot diseases", "sap feeders", "wood borers"], "other_damage"]
    - column: geometry
      action: unique
projection: EPSG:5070
generate_time_combinations: false
scale: 30
strata_columns: ['dca_cat']
test_ratio: 0.1
validate_ratio: 0.2
