trainer:
    callbacks:
      - class_path: callbacks.LogTestCallback
    #   - class_path: callbacks.SaveTestCallback
    precision: 32-true
    devices: 1
criterion:
    class_path: CrossEntropyLoss
activation:
    class_path: Sigmoid
ckpt_path: epoch=0096_val_loss=0.999_before_of.ckpt