trainer:
    callbacks:
      - class_path: callbacks.LogTestCallback
      - class_path: callbacks.SaveTestCallback
    precision: 32-true
    devices: 1
criterion:
    class_path: GeneralizedDiceLoss
activation:
    class_path: Sigmoid
