back_step: null
end_date: null
file_type: ZARR
fraction: null
generate_annotation_data: true
generate_image_chip_data: true
generate_square_samples: true
generate_time_combinations: false
generate_train_test_split: true
geo_file_path: shapes/ads_damage_1990-2022
groupby_columns: ["year"]
filter_columns: ["dca_cat"]
filter_operators: ["!="]
filter_values: [['multi-agent "complexes"', "cankers", "rusts"]]
io_limit: 32
log_name: sample
log_path: logs/ads_damage_1990-2022_14k_v0
look_years: 2
meta_data_path: samples/ads_damage_1990-2022_14k_v0/meta_data
pixel_edge_size: 256
method: centroid
num_points: 2048
num_strata: null 
num_workers: 40
predict_ratio: 0.5
predict_sample_path: samples/ads_damage_1990-2022_14k_v0/predict_sample.npy
projection: EPSG:5070
start_date: null
strata_columns: ['dca_cat']
strata_map_path: samples/ads_damage_1990-2022_14k_v0/strata_map.yaml
strata_scale: null
test_ratio: 0.2
test_sample_path: samples/ads_damage_1990-2022_14k_v0/test_sample.npy
train_samplegit status_path: samples/ads_damage_1990-2022_14k_v0/train_sample.npy
validate_ratio: 0.2
validate_sample_path: samples/ads_damage_1990-2022_14k_v0/validate_sample.npy