model:
    class_path: models.prithvi.PrithviHeadlessCDiff
    init_args:
        view_size: 16
        prithvi_path: src/models/backbones/prithvi/Prithvi_100M.pt
        prithvi_params:
            model_args:
                decoder_depth: 8
                decoder_embed_dim: 512
                decoder_num_heads: 16
                depth: 12
                embed_dim: 768
                img_size: 256
                in_chans: 6
                num_frames: 3
                num_heads: 12
                patch_size: 16
                tubelet_size: 1
        prithvi_freeze: false
data:
    class_path: dataloaders.ChipsDataModule
    init_args:
        batch_size: 32
        num_workers: 16 
        chip_size: 256
        time_step: 3
