datetime_column: "LT_YOD"
file_type: ZARR
fraction: null
gee_workers: 42
gee_stratafied_config: null
groupby_columns: []
io_limit: 32
look_range: 2
method: centroid
num_points: 1
num_workers: 64
overwrite: false
pixel_edge_size: 256
postprocess_actions: []
predict_ratio: 0.0
preprocess_actions: []
projection: EPSG:5070
sample_toggles:
    preprocess_data: true
    stratified_sample: true
    generate_squares: true
    postprocess_data: false
    generate_time_combinations: false
    generate_train_test_splits: false
scale: 30
strata_columns: ["LT_YOD", 'landCover1', 'percentage', 'agent']
test_ratio: 0.0
validate_ratio: 0.0
time_step: 3
