model:
    class_path: models.prithvi.PrithviEmbed
    init_args:
        prithvi_ckpt_path: src/models/backbones/prithvi/PrithviGlobal.pt
        # prithvi_ckpt_path: null
        prithvi_params:
            input_size: [2, 256, 256]
            patch_size: [1, 16, 16]
            in_chans: 6
            embed_dim: 1024
            coords_encoding: []
            # coords_encoding:
            #     - time
            #     - location
        reshape: false
        freeze_encoder: true
    # class_path: models.prithvi.PrithviDecoder3dUNet
    # init_args:
    #     num_classes: 1
    #     num_channels: 6
    #     num_frames: 2
    #     kernel_size: [1, 3, 3]
    #     stride: 1
    #     padding: [0, 1, 1]
    #     prithvi_ckpt_path: src/models/backbones/prithvi/PrithviGlobal.pt
    #     # prithvi_ckpt_path: null
    #     prithvi_params:
    #         input_size: [2, 256, 256]
    #         patch_size: [1, 16, 16]
    #         in_chans: 128
    #         embed_dim: 1024
    #         coords_encoding: []
    #         # coords_encoding:
    #         #     - time
    #         #     - location
    #     freeze_encoder: False
    # class_path: models.prithvi.PrithviFCN
    # init_args:
    #     num_classes: 1
    #     prithvi_ckpt_path: src/models/backbones/prithvi/PrithviGlobal.pt
    #     # prithvi_ckpt_path: null
    #     prithvi_params:
    #         input_size: [2, 64, 64]
    #         patch_size: [1, 16, 16]
    #         in_chans: 6
    #         embed_dim: 1024
    #         coords_encoding: []
    #         # coords_encoding:
    #         #     - time
    #         #     - location
    #     freeze_encoder: False
    # class_path: models.unet3d.UNet3D
    # init_args:
    #     n_channels: 6
    #     n_classes: 2
data:
    class_path: dataloaders.generic_chips_dataset.GenericChipsDataModule
    init_args:
        predict_sample_path: /home/ceoas/truongmy/emapr/sundial/samples/all_glkn/filtered.npy
        batch_size: 32
        num_workers: 4
        chip_size: 256
        time_step: 1
        # extension_config:
        #     load_meta_data: true
        #     extensions:
        #         - class_path: dataloaders.generic_chips_dataset_ext.MultiYearDayFromMeta
        #           init_args:
        #             year_col: yod
        #             year_range: 4
        #             month_day: 08-15
        #             forward: true
        #         - class_path: dataloaders.generic_chips_dataset_ext.LatLonFromMeta
        # dynamic_transform_config:
        #     transforms:
        #         - class_path: transforms.RandomAffineAugmentation
        #           image_only: false
        static_transform_config:
            transforms:
                - class_path: transforms.SingleClass
                  init_args:
                        class_index: 6
                  targets: ["anno"]
                - class_path: torch.nn.AvgPool2d
                  init_args:
                      kernel_size: 16
                      divisor_override: 1
                  methods: ["predict"]
                  targets: ["anno"]
                - class_path: transforms.Flatten
                  init_args:
                      start_dim: 1
                  methods: ["predict"]
                  targets: ["anno"]
                - class_path: transforms.ReverseTime
                  init_args:
                      dim: 1
                  methods: ["predict"]
                  targets: ["chip"]
