annotator: multi_year_xarr_annotator
annotator_kwargs:
    year_range: [1995, 2019]
datetime_column: year
file_type: ZARR
gee_workers: 42
ee_image_factory: lt_medoid_image_factory
io_limit: 32
indexer: time_window_split_class_filter
indexer_kwargs:
    time_range: [1, 25]
    time_step: 1
    class_filters: [
        [null, null],
        [null, null],
        [null, null],
        [null, null],
        [null, null],
        [null, null],
        [0.01, null],
        [null, null],
        [null, null],
        [null, null],
    ]
method: covering_grid
num_points: null
num_workers: 32
overwrite: false
parser_kwargs:
    look_range: 24
pixel_edge_size: 256
postprocess_actions: ["class_counts", "band_mean_stdv"]
preprocess_actions:
    - column: year
      action: ">="
      targets: 1994
    - column: year
      action: "<"
      targets: 2019
    - column: change_occ
      action: "=="
      targets: 'true'
projection: EPSG:5070
scale: 30
class_columns: ["agent_01"]
split_ratios: [.2, .05]
