model:
    class_path: SundialPrithvi
    init_args:
        num_classes: 61 
        view_size: 16
        upscale_depth: 4
        upscale_reduction_factor: 2
        prithvi_path: src/backbones/prithvi/Prithvi_100M.pt
        prithvi_params:
            model_args:
                decoder_depth: 8
                decoder_embed_dim: 512
                decoder_num_heads: 16
                depth: 12
                embed_dim: 768
                img_size: 256
                in_chans: 6
                num_frames: 6
                num_heads: 12
                patch_size: 16
                tubelet_size: 1
            train_params:
                mask_ratio: 0.0
data:
    class_path: ChipsDataModule
    drop_duplicates: ["square_name"]
    init_args:
        batch_size: 32
        num_workers: 0
        means:
            - 775.2290211032589
            - 1080.992780391705
            - 1228.5855250417867
            - 2497.2022620507532
            - 2204.2139147975554
            - 1610.8324823273745
        stds:
            - 1281.526139861424
            - 1270.0297974547493
            - 1399.4802505642526
            - 1368.3446143747644
            - 1291.6764008585435
            - 1154.505683480695
        anno_data_path: data/samples/ads_damage_1990-2022/anno_data.zarr
        back_step: null
        base_year: null
        chip_data_path: data/samples/ads_damage_1990-2022/chip_data.zarr
        chip_size: 256
        file_type: zarr
        predict_sample_path: data/samples/ads_damage_1990-2022/predict_sample.zarr
        test_sample_path: data/samples/ads_damage_1990-2022/test_sample.zarr
        train_sample_path: data/samples/ads_damage_1990-2022/train_sample.zarr
        validate_sample_path: data/samples/ads_damage_1990-2022/validate_sample.zarr
trainer:
    accelerator: cuda 
    callbacks:
      - class_path: PredictionWriter
        init_args:
            output_dir: logs/ads_damage_1990-2022/predictions
            write_interval: batch
    inference_mode: true
    log_every_n_steps: 16
    logger:
        class_path: ExperimentLogger
        init_args:
            name: fit
            save_dir: logs/ads_damage_1990-2022
    max_epochs: 128
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0001
        weight_decay: 0.01

lr_scheduler:
    class_path: torch.optim.lr_scheduler.StepLR
    init_args:
        step_size: 16
