data:
  class_path: ChipsDataModule
  init_args:
    anno_data_path: samples/ads_damage_1990-2022/anno_data.zarr
    back_step: null
    base_year: null
    chip_data_path: samples/ads_damage_1990-2022/chip_data.zarr
    chip_size: 256
    file_type: zarr
    predict_sample_path: samples/ads_damage_1990-2022/predict_sample.zarr
    test_sample_path: samples/ads_damage_1990-2022/test_sample.zarr
    train_sample_path: samples/ads_damage_1990-2022/train_sample.zarr
    validate_sample_path: samples/ads_damage_1990-2022/validate_sample.zarr
trainer:
  accelerator: cuda
  callbacks:
  - class_path: ModelCheckpoint
    init_args:
      auto_insert_metric_name: false
      dirpath: checkpoints/ads_damage_1990-2022_TEST
      every_n_epochs: 2
      filename: epoch-{epoch:02d}_val_loss-{val_loss:.2f}_v-
      monitor: val_loss
      save_top_k: 4
  inference_mode: false
  logger:
    class_path: TensorBoardLogger
    init_args:
      name: validate
      save_dir: sundial/logs/ads_damage_1990-2022_TEST
