trainer:
    callbacks:
      - class_path: callbacks.SaveTensorCallback
    precision: 32-true
    devices: 1
activation:
    class_path: Softmax
    init_args:
        dim: 1
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0106_val_loss=0.679_unet3d_q1_w2.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0125_val_loss=0.680_fcn_frozen_encoder_q1_w2.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0116_val_loss=0.670_fcn_unfrozen_encoder_q1_w2.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0124_val_loss=0.683_fcn_random_encoder_q1_w2.ckpt 

ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0065_val_loss=0.240_3cls_glkn_unet3d_q1_w2_full.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0086_val_loss=0.194_fcn_frozen_encoder_q1_w2_full.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0096_val_loss=0.240_fcn_unfrozen_encoder_q1_w2_full.ckpt
# ckpt_path: /ceoas/emapr/sundial/checkpoints/3cls_glkn/epoch=0106_val_loss=0.240_fcn_random_encoder_q1_w2_full.ckpt