annotator: multi_year_xarr_annotator
annotator_kwargs:
    year_range: [1994, 2020]
buffer: 0
datetime_column: year
file_type: ZARR
gee_workers: 42
ee_image_factory: lt_medoid_image_factory
io_limit: 8
indexer: time_window_split_class_filter
indexer_kwargs:
    time_range: [2, 28]
    time_step: 1
    anno_offset: 2
    class_filters: [
        [0.01, null],
        [null, null],
        [null, null],
        [0.01, null],
        [null, null],
        [null, null],
        [0.01, null],
        [0.01, null],
        [null, null],
        [null, null],
    ]
method: covering_grid
num_points: null
num_workers: 4
overwrite: false
parser_kwargs:
    look_range: 29
pixel_edge_size: 224
postprocess_actions: ["class_counts", "band_mean_stdv"]
preprocess_actions:
    - column: year
      action: ">"
      targets: 1993
    - column: year
      action: "<"
      targets: 2020
    - column: change_occ
      action: "=="
      targets: 'true'
projection: EPSG:5070
scale: 30
squares_config:
    overlap: 16
    year_offset: 2
class_columns: ["agent_01"]
split_ratios: [.2, .05]
