trainer:
    callbacks:
      - class_path: callbacks.LogTestCallback
      - class_path: callbacks.LogBinaryExtCallback
    precision: 32-true
    devices: 1
criterion:
    class_path: DiceLoss
    init_args:
        multiclass: true
activation:
    class_path: Softmax