model:
    class_path: models.prithvi.PrithviDecoder3dUNet
    init_args:
        num_classes: 2
        num_channels: 6
        kernel_size: [1, 3, 3]
        stride: 1
        padding: [0, 1, 1]
        # prithvi_ckpt_path: '/home/ceoas/truongmy/emapr/sundial/src/models/backbones/prithvi/Prithvi_EO_V2_300M.pt'
        prithvi_ckpt_path: null
        prithvi_params:
            img_size: 64
            patch_size: [1, 4, 4]
            in_chans: 128
            num_frames: 2
            embed_dim: 1024
            coords_encoding: []
            encoder_only: false
            # coords_encoding:
            #     - time
            #     - location
        freeze_encoder: false
data:
    class_path: dataloaders.generic_chips_dataset.GenericChipsDataModule
    init_args:
        batch_size: 32
        num_workers: 4
        chip_size: 256
        time_step: 2
        # extension_config:
        #     load_meta_data: true
        #     extensions:
        #         - class_path: dataloaders.generic_chips_dataset_ext.MultiYearDayFromMeta
        #           init_args:
        #             year_col: yod
        #             year_range: 4
        #             month_day: 08-15
        #             forward: true
        #         - class_path: dataloaders.generic_chips_dataset_ext.LatLonFromMeta
        dynamic_transform_config:
            include_original: false
            transforms:
              - class_path: transforms.RandomCropAndAffine
                init_args:
                    size: [64, 64]
                image_only: false
        static_transform_config:
            transforms:
              - class_path: torchvision.transforms.v2.CenterCrop
                init_args:
                    size: [128, 128]
                methods: ["train"]
                targets: ["chip", "anno"]
              - class_path: torchvision.transforms.v2.CenterCrop
                init_args:
                    size: [64, 64]
                methods: ["validate", "test"]
                targets: ["chip", "anno"]
                