trainer:
    callbacks:
      - class_path: callbacks.LogTestCallback
    #   - class_path: callbacks.SaveTestCallback
    #   - class_path: callbacks.SaveEmbedCallback
    precision: 32-true
    devices: 1
# ckpt_path: null
criterion:
    class_path: DiceLoss
activation:
    class_path: Sigmoid