trainer:
    callbacks:
      - class_path: callbacks.LogTrainCallback
      - class_path: callbacks.LogTrainBinaryExtCallback
      - class_path: StochasticWeightAveraging
        init_args:
            swa_lrs: 0.0001
            device: null
    max_epochs: 1
    enable_progress_bar: false
    # strategy: ddp_find_unused_parameters_true
    strategy: auto
    devices: 1
    num_nodes: 1
    accumulate_grad_batches: 8
    log_every_n_steps: 8
    precision: bf16-mixed
model_checkpoint:
    monitor: precision
    mode: max
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.001
lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
        T_max : 128
criterion:
    class_path: GeneralzedDiceBoundaryLoss
    init_args:
        alpha: 0.05
activation:
    class_path: Sigmoid
data:
    init_args:
        transform_config:
            include_original: true
            transforms:
              - class_path: torchvision.transforms.RandomRotation
                init_args:
                    degrees: 360
                image_only: true
              - class_path: torchvision.transforms.RandomHorizontalFlip
                init_args:
                    p: 1
                image_only: true
              - class_path: torchvision.transforms.RandomVerticalFlip
                init_args:
                    p: 1
                image_only: true