datetime_column: "yod"
file_type: ZARR
fraction: null
gee_workers: 42
gee_stratafied_config: null
groupby_columns: ["yod"]
io_limit: 32
look_range: 3
method: centroid
num_points: null
num_workers: 32
overwrite: false
pixel_edge_size: 256
postprocess_actions: []
preprocess_actions:
    - column: predicted
      action: "in"
      targets: ['%_Clearcut']
    - column: area
      action: ">="
      targets: 73984.28666815045
projection: EPSG:5070
generate_time_combinations: false
scale: 30
strata_columns: ["predicted"]
split_ratios: [.2, .02]
