model:
    class_path: PrithviFCN
    init_args:
        num_classes: 1
        view_size: 16
        upscale_depth: 2
        prithvi_path: src/backbones/prithvi/Prithvi_100M.pt
        prithvi_params:
            model_args:
                decoder_depth: 8
                decoder_embed_dim: 512
                decoder_num_heads: 16
                depth: 12
                embed_dim: 768
                img_size: 256
                in_chans: 6
                num_frames: 3
                num_heads: 12
                patch_size: 16
                tubelet_size: 1
            train_params:
                mask_ratio: 0.0
        prithvi_freeze: true
        criterion:
            class_path: torch.nn.BCEWithLogitsLoss
            init_args:
                reduction: sum
data:
    class_path: ChipsDataModule
    init_args:
        batch_size: 16
        num_workers: 64
        chip_size: 256
trainer:
    callbacks:
      - class_path: PrithviFCNCallbacks
    max_epochs: 256
    strategy: ddp_find_unused_parameters_true
    devices: 2
    num_nodes: 1
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0005
lr_scheduler:
    class_path: torch.optim.lr_scheduler.StepLR
    init_args:
        step_size: 64
        gamma: 0.5