file_type: ZARR
fraction: null
gee_workers: 42
gee_stratafied_config: null
groupby_columns: ["year"]
io_limit: 32
look_range: 6
method: centroid_shift
num_points: 16384
num_workers: 64
overwrite: false
pixel_edge_size: 256
postprocess_actions: []
predict_ratio: 0.5
preprocess_actions:
    - column: dca_cat
      action: "=="
      targets: ["bark beetles"]
projection: EPSG:5070
sample_toggles:
    preprocess_data: true
    stratified_sample: true
    generate_squares: true
    postprocess_data: false
    generate_time_combinations: false
    generate_train_test_splits: true
scale: 30
strata_columns: ['dca_cat']
test_ratio: 0.02
validate_ratio: 0.2
time_step: 3
