trainer:
    callbacks:
      - class_path: LogTestCallback
      - class_path: SaveTestCallback
    precision: 16-mixed
    devices: 1
ckpt_path: null 
verbose: true
criterion:
    class_path: FocalLoss
    init_args:
        reduction: sum
    custom: false
activation:
    class_path: Sigmoid
