trainer:
    callbacks:
      - class_path: callbacks.LogTrainCallback
      - class_path: callbacks.LogTrainMulticlassExtCallback
      - class_path: StochasticWeightAveraging
        init_args:
            swa_lrs: 0.0001
            device: null
    max_epochs: 256
    strategy: ddp_find_unused_parameters_true
    devices: 2
    num_nodes: 1
    accumulate_grad_batches: 8
    precision: bf16-mixed
    gradient_clip_val: 5
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0001
lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
        T_max : 16
criterion:
    class_path: CrossEntropyLoss
    init_args:
        weight:
            - 1.0
            - 0.7501836884643645
            - 0.0025064164014390413
            - 0.013133015191078297
            - 0.04686549694180829
activation:
    class_path: Softmax
    init_args:
        dim: 1
# data:
#     init_args:
#         transform_config:
#             include_original: true
#             transforms:
#               - class_path: torchvision.transforms.RandomRotation
#                 init_args:
#                     degrees: 360
#                 apply_to_anno: true
#               - class_path: torchvision.transforms.RandomHorizontalFlip
#                 init_args:
#                     p: 1
#                 apply_to_anno: true
#               - class_path: torchvision.transforms.RandomVerticalFlip
#                 init_args:
#                     p: 1
#                 apply_to_anno: true
#               - class_path: GeoColorJitter
#                 init_args:
#                     brightness: 0.1
#                     contrast: 0.001
#                     saturation: 0.001
#                     hue: 0.001
