trainer:
    callbacks:
      - class_path: callbacks.LogTrainCallback
      - class_path: callbacks.LogTrainPixelwiseExtCallback
      - class_path: StochasticWeightAveraging
        init_args:
            swa_lrs: 0.0001
            device: null
    max_epochs: 64
    strategy: auto
    devices: 1
    num_nodes: 1
    accumulate_grad_batches: 16
    precision: bf16-mixed
    gradient_clip_val: 5
optimizer:
    class_path: torch.optim.AdamW
    init_args:
        lr: 0.0001
lr_scheduler:
    class_path: torch.optim.lr_scheduler.CosineAnnealingLR
    init_args:
        T_max : 16
criterion:
    class_path: CrossEntropyLoss
    init_args:
        weight: [1.0, 0.18237304, 0.39916356, 0.22545021, 0.41653142]
activation:
    class_path: Softmax
    init_args:
        dim: 1
data:
    init_args:
        transform_config:
            include_original: false
            transforms:
                - class_path: TimeStepDifference
