trainer:
    callbacks:
      - class_path: callbacks.LogTestCallback
      - class_path: callbacks.SaveTestCallback
      - class_path: callbacks.LogTrainPixelwiseExtCallback
    precision: 16-mixed
    devices: 1
ckpt_path: null
verbose: true
criterion:
    class_path: CrossEntropyLoss
    init_args:
        reduction: sum
activation:
    class_path: Softmax
    init_args:
        dim: 1