annotator: single_xarr_annotator
annotator_kwargs: {}
class_columns: ['predicted']
datetime_column: yod
ee_image_factory: lt_medoid_image_factory
factory_kwargs: {}
file_type: ZARR
gee_workers: 40
image_reshaper: unstack_band_years
indexer: train_validate_test_split
indexer_kwargs: {}
io_limit: 32
meta_data_parser: medoid_from_year
method: centroid
num_points: 2480
num_workers: 64
overwrite: false
parser_kwargs:
  end_day: 1
  end_month: 9
  look_range: 3
  start_day: 1
  start_month: 7
pixel_edge_size: 256
postprocess_actions:
- band_mean_stdv
preprocess_actions: []
projection: EPSG:5070
reshaper_kwargs: {}
scale: 30
split_ratios:
- 0.2
- 0.02
squares_config: {}
